import { GamePhase } from '../game/types/gameState.types';

// Extend the Prisma client to include our custom models
// Extend the Prisma client to include our custom models
// Note: GameState is now generated by Prisma from the schema, so this manual extension is likely redundant and causing conflicts.
// It is kept commented out for reference in case specific overrides are needed.
/*
declare module '@prisma/client' {
  interface PrismaClient {
    gameState: {
      findFirst: () => Promise<GameState | null>;
      create: (args: { data: Omit<GameState, 'id' | 'createdAt' | 'updatedAt'> & { id?: string } }) => Promise<GameState>;
      update: (args: { where: { id: string }; data: Partial<Omit<GameState, 'id' | 'createdAt'>> }) => Promise<GameState>;
    };
  }
}
*/

// Define the GameState model type
export interface GameState {
  id: string;
  currentDate: string;
  gameSpeed: number;
  isPaused: boolean;
  season: number;
  phase: GamePhase;
  activeCompetitions: string[];
  activeClubs: string[];
  userClubId: string | null;
  lastSimulatedDate: string | null;
  version: string;
  createdAt: Date;
  updatedAt: Date;
}
